spring:
  datasource:
    url: jdbc:postgresql://localhost
    username: postgres
    password: password

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: DEBUG